#!/bin/bash

# Reset the working directory to the script's path
my_abs_path=$(readlink -f "$0")
my_dirname=$(dirname $my_abs_path)
cd "$my_dirname"

function abort_on_error () {
    if [[ $? -ne "0" ]]; then
        echo FAILED: $1
        exit 1
    fi
}

# TODO Reenable Lite multiprocessing after we figure out why it was
# causing tester processes to hang.
lite_multiprocess=""
# lite_multiprocess="--processes=4 --process-timeout=1200"

# Attempts to abstract this better failed due to bash's impossible
# quoting mechanisms.
function test_inference_program_in_lite() {
    infer=$1
    echo nosetests $lite_multiprocess -c inference-quality.cfg --eval-attr="\"not slow and (not backend or backend in ['lite', 'any'])\"" --tc=get_ripl:lite --tc=ignore_inference_quality:true --tc=infer:"\"$infer\""
    nosetests $lite_multiprocess -c inference-quality.cfg --eval-attr="not slow and (not backend or backend in ['lite', 'any'])" --tc=get_ripl:lite --tc=ignore_inference_quality:true --tc=infer:"$infer"
    abort_on_error "$infer in Lite"
}

function test_inference_program_in_puma() {
    infer=$1
    echo nosetests -c inference-quality.cfg --tc=ignore_inference_quality:true --eval-attr="\"not slow and (not backend or backend in ['puma', 'any'])\"" --tc=infer:"\"$infer\"" --tc=get_ripl:puma
    nosetests -c inference-quality.cfg --tc=ignore_inference_quality:true --eval-attr="not slow and (not backend or backend in ['puma', 'any'])" --tc=infer:"$infer" --tc=get_ripl:puma
    abort_on_error "$infer in Puma"
}

# TODO Reenable multiprocessing for puma, after nose is made robust to
# worker processes blowing up.
echo nosetests -c crashes.cfg --tc=get_ripl:puma
nosetests -c crashes.cfg --tc=get_ripl:puma
abort_on_error "(mh default one 3) in Puma"

echo nosetests $lite_multiprocess -c crashes-base.cfg --tc=get_ripl:lite --eval-attr="\"not slow and (not backend or backend in ['lite', 'any'])\""
nosetests $lite_multiprocess -c crashes-base.cfg --tc=get_ripl:lite --eval-attr="not slow and (not backend or backend in ['lite', 'any'])"
abort_on_error "(mh default one 3) in Lite"

test_inference_program_in_lite "(rejection default all 1)"
test_inference_program_in_lite "(func_pgibbs default ordered 3 3)"
test_inference_program_in_lite "(pgibbs default ordered 3 3)"
test_inference_program_in_lite "(meanfield default one 3 3)"

test_inference_program_in_puma "(func_mh default one 3)"
test_inference_program_in_puma "(func_pgibbs default ordered 3 3)"
