#!/bin/bash

# Copyright (c) 2013, 2014 MIT Probabilistic Computing Project.
#
# This file is part of Venture.
#
# Venture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Venture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Venture.  If not, see <http://www.gnu.org/licenses/>.

# Reset the working directory to the script's path
my_abs_path=$(readlink -f "$0")
my_dirname=$(dirname $my_abs_path)
cd "$my_dirname"

function abort_on_error () {
    if [[ $? -ne "0" ]]; then
        echo FAILED: $1
        exit 1
    fi
}

# Attempts to abstract this better failed due to bash's impossible
# quoting mechanisms.
function test_inference_program_in_lite() {
    infer=$1
    echo nosetests --processes=4 --process-timeout=6000 -c inference-quality.cfg --tc=get_ripl:lite --tc=infer:"\"$infer\""
    nosetests --processes=4 --process-timeout=6000 -c inference-quality.cfg --tc=get_ripl:lite --tc=infer:"$infer"
    abort_on_error "$infer in Lite"
}

test_inference_program_in_lite "(mh default one 50)"
test_inference_program_in_lite "(rejection default all 1)"
test_inference_program_in_lite "(func_pgibbs default ordered 2 2)"
# test_inference_program_in_lite "(pgibbs default ordered 10 3)"
test_inference_program_in_lite "(meanfield default one 10 10)"
