#!/bin/bash

# Copyright (c) 2015 MIT Probabilistic Computing Project.
#
# This file is part of Venture.
#
# Venture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Venture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Venture.  If not, see <http://www.gnu.org/licenses/>.

if [[ -z $1 ]]; then
    echo "Usage: refman-changelog commit

Print changes to files that have significant impact on the reference
manual since the specified commit.

A good commit to choose might be the one that occurred on the date
of the last update to the online edition of the reference manual,
which can be ascertained by invoking

  ls -l /afs/csail.mit.edu/proj/probcomp/www/data/venture/edge/reference/

at any CSAIL machine.

Must be invoked from the root of the Venture checkout."
    exit 1
fi

commit=$1

git diff $commit..HEAD -- backend/lite/builtin.py             # Lite modeling SPs
git diff $commit..HEAD -- backend/lite/inference_sps.py       # Inference SPs
git diff $commit..HEAD -- python/lib/sivm/macro.py            # Macros
git diff $commit..HEAD -- python/lib/engine/macro.py          # Inference-only macros
git diff $commit..HEAD -- backend/new_cxx/src/builtin.cxx     # Puma modeling SPs
git diff $commit..HEAD -- script/venture                      # Invocation
echo "Don't forget to check the reference manual repository"
