#!/usr/bin/env python

import os.path
import sys

import copyright

class VentureCopyCorrector(copyright.CopyCorrector):
  def claim_regex(self):
    return r'^Copyright \(c\) ([-0-9 ,]+) MIT Probabilistic Computing Project\.$'
  def claim_format(self):
    return " Copyright (c) %s MIT Probabilistic Computing Project."
  def notice(self):
    return """\
 This file is part of Venture.

 Venture is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 Venture is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with Venture.  If not, see <http://www.gnu.org/licenses/>."""
  def default_default_year(self):
    return "2015"

# TODO In Venture, .y files are lemonade grammars, which take /* */ comments
def venture_comment_syntax_convention(filename):
  (_, extension) = os.path.splitext(filename)
  if extension in [".cfg", ".cmake", ".supp"]:
    # .cfg is nose configs
    # .cmake is Cmake files (they are all third-party anyway)
    # .supp is Valgrind suppression files (they are all third-party anyway)
    return copyright.repeated_character_comment_syntax('#', 1, 1)
  elif extension in [".vnt"]:
    return copyright.repeated_character_comment_syntax(';', 1, 3)
  elif extension in [".vnts"]:
    return copyright.repeated_character_comment_syntax('/', 2, 2)
  return None

if __name__ == "__main__":
  copyright.process_file(sys.argv[1], VentureCopyCorrector, venture_comment_syntax_convention)
