#!/bin/bash

# Copyright (c) 2014, 2015, 2016 MIT Probabilistic Computing Project.
#
# This file is part of Venture.
#
# Venture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Venture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Venture.  If not, see <http://www.gnu.org/licenses/>.

set -Ceu

release=${1:-`python setup.py --version`}
if [ -z "$release" ]; then
    echo >&2 Could not determine a release number, exiting
    exit 1
fi

script/release-tarball

python setup.py sdist

dist_name=xventure-${release} # I only need this for the length anyway

diff -u <(tar -tf ../venture-$release.tgz | cut -c 11- | sort) <(tar -ztf dist/venture-$release.tar.gz | cut -c ${#dist_name}- | sort)
