#!/usr/bin/python

# Copyright (c) 2013, MIT Probabilistic Computing Project.
# 
# This file is part of Venture.
# 	
# Venture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 	
# Venture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 	
# You should have received a copy of the GNU General Public License along with Venture.  If not, see <http://www.gnu.org/licenses/>.

import string
from venture.lite.builtin import builtInSPsList

def flags(psp):
  ans = []
  if psp.isRandom():
    ans += ["stochastic"]
  else:
    ans += ["deterministic"]
  if psp.canAbsorb():
    ans += ["constrainable"]
  if psp.childrenCanAAA():
    ans += ["children can absorb at applications"]
  if psp.canEnumerate():
    ans += ["enumerable"]
  if psp.hasVariationalLKernel():
    ans += ["variationable"]
  # Simulation kernels and delta kernels are unused right now
  return ans

for (name,sp) in builtInSPsList():
  print sp.description(name)
  print "  " + string.join(flags(sp.outputPSP), ", ")
