#!/bin/bash -xe

# Copyright (c) 2014 MIT Probabilistic Computing Project.
#
# This file is part of Venture.
#
# Venture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Venture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Venture.  If not, see <http://www.gnu.org/licenses/>.

# Create a new virtual environment to install Venture (and its Python dependencies):
virtualenv env.d

# If (some) Python dependencies were pre-installed these can be used by typing
virtualenv --system-site-packages env.d

# Activate the environment, and install any remaining dependencies
source env.d/bin/activate
pip install -r requirements.txt

# Be sure to put nose into the virtualenv, so it can find its packages
pip install --ignore-installed nose

# [Optional] Install ggplot (needed for the built-in plotting facilities)
pip install ggplot
