#!/bin/bash -xe

# Copyright (c) 2014 MIT Probabilistic Computing Project.
#
# This file is part of Venture.
#
# Venture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Venture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Venture.  If not, see <http://www.gnu.org/licenses/>.

# Get system dependencies
sudo apt-get install -y libboost-all-dev libgsl0-dev python-pip ccache libfreetype6-dev
# Must update distribute before requirements.txt install
sudo pip install -U distribute

# [Optional] Get Python dependencies (faster to install prepackaged than via pip)
# Also pulls in required external libraries
# HOWEVER, version skew problems have been reported if installing
# python-numpy and python-scipy via apt-get on older versions of Ubuntu
sudo apt-get install -y python-pyparsing python-flask python-requests python-numpy python-matplotlib python-scipy python-zmq ipython

# [Optional] Get dependencies for ggplot (needed for the built-in plotting facilities)
# Note: on older versions of Ubuntu, install them via pip (see "Install ggplot" below)
sudo apt-get install -y python-pandas python-patsy

# [Optional] Get dependencies for networkx (needed for some scaffold debugging facilities)
sudo apt-get install -y libgraphviz-dev
