#!/bin/bash -xe

# Get system dependencies
sudo apt-get install -y libboost-all-dev libgsl0-dev python-pip ccache libfreetype6-dev
# Must update distribute before requirements.txt install
sudo pip install -U distribute

# [Optional] Get Python dependencies (faster to install prepackaged than via pip)
# Also pulls in required external libraries
# HOWEVER, version skew problems have been reported if installing
# python-numpy and python-scipy via apt-get on older versions of Ubuntu
sudo apt-get install -y python-pyparsing python-flask python-requests python-numpy python-matplotlib python-scipy python-zmq ipython

# [Optional] Get dependencies for ggplot (needed for the built-in plotting facilities)
# Note: on older versions of Ubuntu, install them via pip (see "Install ggplot" below)
sudo apt-get install -y python-pandas python-patsy

# [Optional] Get dependencies for networkx (needed for some scaffold debugging facilities)
sudo apt-get install -y libgraphviz-dev
