#!/bin/bash

# Reset the working directory to the directory above the script's path
my_abs_path=$(readlink -f "$0")
root_dirname=$(dirname $(dirname $my_abs_path))
echo "$root_dirname"
cd $root_dirname

release=0.2.1
if [[ ! -z $1 ]]; then
    release=$1
fi

tar --create --verbose --gzip --file ../venture-$release.tgz --directory .. \
    --exclude=.git \
    --exclude=.gitignore \
    --exclude=*.pyc \
    --exclude=build \
    --exclude=CMakeCache.txt \
    --exclude=CMakeFiles \
    --exclude=cmake_install.cmake \
    --exclude=env.d \
    --exclude=*~ \
    --exclude=valgrind-python.supp \
    --exclude=Makefile \
    --exclude=CMakeLists.txt \
    --exclude=*.so \
    --exclude=testEigen \
    --exclude=cmake \
    --exclude=htmlcov \
    --exclude=.gdbinit \
    --exclude=backend/hs \
    --exclude=CP1-Quad-Rotor \
    --exclude=.coverage \
    --exclude=.idea \
    --exclude=venture-*.tgz \
    --exclude=venture-*.tar.gz \
    --exclude=venture-*.tar \
    Venturecxx/
