#!/bin/bash

# Copyright (c) 2013, 2014, 2015 MIT Probabilistic Computing Project.
#
# This file is part of Venture.
#
# Venture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Venture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Venture.  If not, see <http://www.gnu.org/licenses/>.

# Reset the working directory to the directory above the script's path
my_abs_path=$(readlink -f "$0")
root_dirname=$(dirname $(dirname $my_abs_path))
echo "$root_dirname"
cd $root_dirname

release=`grep "version_str=" script/venture | cut -d '"' -f 2`
if [[ ! -z $1 ]]; then
    release=$1
fi
if [[ -z $release ]]; then
    echo Could not determine a release number, exiting
    exit 1
fi

echo Making a tarball marked version $release

tar --create --verbose --gzip --file ../venture-$release.tgz --directory .. \
    --exclude=.git \
    --exclude=.gitignore \
    --exclude=.gitmodules \
    --exclude=.gitattributes \
    --exclude=*.pyc \
    --exclude=*.bci \
    --exclude=*.bin \
    --exclude=*.com \
    --exclude=*.ext \
    --exclude=v1-pre-scm/**/todo.txt \
    --exclude=build \
    --exclude=CMakeCache.txt \
    --exclude=CMakeFiles \
    --exclude=cmake_install.cmake \
    --exclude=env.d \
    --exclude=*~ \
    --exclude=.owainnotes.txt \
    --exclude=valgrind-python.supp \
    --exclude=Makefile \
    --exclude=CMakeLists.txt \
    --exclude=*.so \
    --exclude=testEigen \
    --exclude=cmake \
    --exclude=htmlcov \
    --exclude=.gdbinit \
    --exclude=backend/hs \
    `# Excluding Terminal because it's unused and copyright-intermixed` \
    --exclude=demos/jsripl/Terminal \
    --exclude=CP1-Quad-Rotor \
    --exclude=.coverage \
    --exclude=.idea \
    --exclude=.ipynb_checkpoints \
    --exclude=tool/logs \
    --exclude=doc/v1 \
    --exclude=script/release-tarball \
    --exclude=venture-*.tgz \
    --exclude=venture-*.tar.gz \
    --exclude=venture-*.tar.bz2 \
    --exclude=venture-*.tar \
    Venturecxx/

md5sum ../venture-$release.tgz
