#!/bin/bash

# Reset the working directory to the directory above the script's path
my_abs_path=$(readlink -f "$0")
root_dirname=$(dirname $(dirname $my_abs_path))
echo "$root_dirname"
cd $root_dirname

release=`grep "version_str=" script/venture | cut -d '"' -f 2`
if [[ ! -z $1 ]]; then
    release=$1
fi
if [[ -z $release ]]; then
    echo Could not determine a release number, exiting
    exit 1
fi

echo Making a tarball marked version $release

tar --create --verbose --gzip --file ../venture-$release.tgz --directory .. \
    --exclude=.git \
    --exclude=.gitignore \
    --exclude=*.pyc \
    --exclude=build \
    --exclude=CMakeCache.txt \
    --exclude=CMakeFiles \
    --exclude=cmake_install.cmake \
    --exclude=env.d \
    --exclude=*~ \
    --exclude=valgrind-python.supp \
    --exclude=Makefile \
    --exclude=CMakeLists.txt \
    --exclude=*.so \
    --exclude=testEigen \
    --exclude=cmake \
    --exclude=htmlcov \
    --exclude=.gdbinit \
    --exclude=backend/hs \
    --exclude=CP1-Quad-Rotor \
    --exclude=.coverage \
    --exclude=.idea \
    --exclude=.ipynb_checkpoints \
    --exclude=tool/logs \
    --exclude=doc/v1 \
    --exclude=backend/v1-pre-scm \
    --exclude=script/release-tarball \
    --exclude=venture-*.tgz \
    --exclude=venture-*.tar.gz \
    --exclude=venture-*.tar.bz2 \
    --exclude=venture-*.tar \
    Venturecxx/

md5sum ../venture-$release.tgz
