#!/bin/bash

sudo docker run \
  -t                         `# Start a terminal` \
  -i                         `# Interactive` \
  -p 8888:8888               `# Expose IPython notebook server` \
  -p 5900:5900               `# Expose VNC server` \
  -v `pwd`:/root/Venturecxx  `# Map source directory into the container` \
  venture
