#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (c) 2013, MIT Probabilistic Computing Project.
#
# This file is part of Venture.
#
# Venture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Venture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with Venture.  If not, see <http://www.gnu.org/licenses/>.

import sys
import argparse
from venture.ripl.console import run_venture_console
import venture.shortcuts as v

version_str="0.2.2p-beta"

def banner(help=True):
    help_ad = "  `help' for help"
    if not(help):
        help_ad = ""
    print '''
Venture, version {0}  http://probcomp.csail.mit.edu/venture/{1}
Venture is *alpha quality* software.
Expect occasional crashes that wipe out your Venture session.
'''.format(version_str, help_ad).strip()

def server(args):
    banner(False)
    server = v.backend(args.backend).make_ripl_rest_server()
    print "Launching RIPL Server"
    server.run(host='0.0.0.0', port=args.port, debug=True, use_reloader=False)

def client(args):
    banner()
    url = "http://{0}:{1}".format(args.host, args.port)
    print "Connecting to RIPL Server at {0}".format(url)
    run_venture_console(v.make_ripl_rest_client(url))

def puma(args):
    banner()
    local_ripl(args, v.Puma())

def cxx(args):
    banner()
    local_ripl(args, v.CXX())

def lite(args):
    banner()
    local_ripl(args, v.Lite())

def load_library(name):
    import imp
    with open(name, 'rb') as f:
        return imp.load_source(name, name, f)

def local_ripl(args, backend):
    interactive = True
    r = backend.make_combined_ripl()
    if args is not None:
        if args.prelude: r.load_prelude()
        if args.library:
            for l in args.library:
                m = load_library(l)
                if hasattr(m, "__venture_start__"):
                    m.__venture_start__(r)
        if args.lang:
            r.set_mode(args.lang)
        if args.file:
            for f in args.file:
                interactive = False
                r.execute_program_from_file(f)
        if args.eval:
            for e in args.eval:
                interactive = False
                r.execute_program(e)
        if args.interactive:
            interactive = True
    if interactive:
        run_venture_console(r)
    return r

def add_local_args(parser):
    parser.add_argument('--prelude', action='store_true',
                        help = 'load prelude on startup')
    parser.add_argument('-f', '--file', action='append', help="execute the given file")
    parser.add_argument('-e', '--eval', action='append', help="execute the given program")
    parser.add_argument('-i', '--interactive', action='store_true', help="enter interactive interpreter after completing script file")
    parser.add_argument('-l', '--lang', default="church_prime",
                        help="the syntax to interpret in the console (valid values: are \"church_prime\" (default) and \"venture_script\")")
    parser.add_argument('-L', '--library', action='append',
                        help="load a Python file in the local directory.  If the file defines a __venture_start__ function, call it with the ripl to initialize the library.")
    return parser

parser = argparse.ArgumentParser(description='An interactive, Turing-complete probabilistic programming platform')
parser.add_argument('--version', action='version', version='Venture, version %s' % version_str)
subparsers = parser.add_subparsers(title="optional mode")

parser_local = subparsers.add_parser("puma", help="[default] Start a local Venture Puma session",
                                     description="Start a local Venture Puma session")
parser_local.set_defaults(func=puma)
add_local_args(parser_local)

parser_local = subparsers.add_parser("cxx", help="Start a local Venture CXX session",
                                     description="Start a local Venture CXX session")
parser_local.set_defaults(func=cxx)
add_local_args(parser_local)

parser_local = subparsers.add_parser("lite", help="Start a local Venture Lite session",
                                     description="Start a local Venture Lite session")
parser_local.set_defaults(func=lite)
add_local_args(parser_local)

default_port = 8082

parser_server = subparsers.add_parser("server", help="Start a Venture server session",
                                      description="Start a Venture server session")
parser_server.add_argument("backend", default="lite", help="the Venture backend use")
parser_server.add_argument("-p", "--port", type=int, default=default_port,
                           help="the port to listen on (default {0})".format(default_port))
parser_server.set_defaults(func=server)

default_host = '127.0.0.1'

parser_client = subparsers.add_parser("remote", help="Connect to a running Venture server session",
                                      description="Connect to a running Venture server session")
parser_client.add_argument("--host", default=default_host,
                           help="the host to connect to (default {0})".format(default_host))
parser_client.add_argument("-p", "--port", type=int, default=default_port,
                           help="the port to connect on (default {0})".format(default_port))
parser_client.set_defaults(func=client)

if len(sys.argv) == 1:
    # Work around what appears to be a limitation of argparse
    puma(None)
else:
    args = parser.parse_args()
    args.func(args)
