require("sp.jl")

builtInSPs = Dict{Symbol,VentureValue}()
require("deterministic.jl")
require("distributions.jl")
require("csp.jl")
require("msp.jl")
require("conditionals.jl")
require("dstructures.jl")
require("aaa.jl")
require("scope.jl")