#!/bin/bash

# Copyright (c) 2015 MIT Probabilistic Computing Project.
#
# This file is part of Venture.
#
# Venture is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Venture is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Venture.  If not, see <http://www.gnu.org/licenses/>.

case $1 in
curve-fitting|graph_curve_fitting.html)
  (sleep 1 && xdg-open graph_curve_fitting.html) &  # The sleep gives the server enough time to start
  venture server puma
;;
clustering|cluster_crp_mixture.html)
  (sleep 1 && xdg-open cluster_crp_mixture.html) &  # The sleep gives the server enough time to start
  venture server puma
;;
collapsed-clustering|cmvn_crp_mixture.html)
  (sleep 1 && xdg-open cmvn_crp_mixture.html) &  # The sleep gives the server enough time to start
  venture server lite
;;
gp-curve-fitting|gp_curve_fitting.html)
  (sleep 1 && xdg-open gp_curve_fitting.html) &  # The sleep gives the server enough time to start
  python gp_server.py
;;
*)
  cat <<EOF
Usage: demo [demo-name]

Starts the server and browser for the named web demo.

Accepted names are:
- curve-fitting or graph_curve_fitting.html      The curve fitting demo
- clustering or cluster_crp_mixture.html         The clustering demo
- collapsed-clustering or cmvn_crp_mixture.html  The clustering demo with collapsed Gaussian clusters
- gp-curve-fitting or gp_curve_fitting.html      The Gaussian process curve fitting demo
EOF
;;
esac
