
#ifndef VENTURE___HEADER_H
#define VENTURE___HEADER_H

#include "HeaderPre.h"
#include "Utilities.h"

const int VENTURECONSTANT__MAX_ALLOWED_NUMBER_OF_SECONDS_FOR_REJECTION_SAMPLING = 5;
const int VENTURE__MAX_TIME_FOR_PAUSED_CONTINUOUS_INFERENCE = 10;

#endif
